### ISSUE TITLE
Mesher handle DEMs with water bodies

### ISSUE THREAD

**Issue by NicWayand** [Chrismarsh/CHM#54]
Allow mesher to handle discontinuous areas (islands)

**Comment by Chrismarsh** [comment]
I think this is properly handled now. Mesher commit https://github.com/Chrismarsh/mesher/commit/589b90912dc86ff16fed95cf4b92b7722d4711a0 now allows multiple rasters to be combined on the fly to create landcover classification information, which can be lookedup at run time for water/no water, or any other important land cover.
