### ISSUE TITLE
Mass Balance module needed

### ISSUE THREAD

**Issue by NicWayand** [Chrismarsh/CHM#99]
Checking basin mass balance at present requires outputting at model time step to check (approaching 60GB for 1 year of vtu output over fortress...). Instead an optional module that keeps track of basin mass balance would be useful. Should help constrain blowing snow model development.

**Comment by ccalvocm** [comment]
Greetings @NicWayand, could you share your check point mass balance please?, did you write them reading the docs?

**Comment by Chrismarsh** [comment]
@ccalvocm The newer versions of CHM can write to ugrid netcdf directly. These can be read with the python uxarray and subset for a domain. I'm not sure how familiar you are with the dask-backed arrays in xarray, but they are a robust way to accumulate N-d arrays over time and space.
